[project]
name = "mcp-server-google-scholar"
version = "0.1.0"
description = "An MCP server for searching and retrieving articles from Google Scholar"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.4.1",
    "scholarly>=1.7.0",
    "asyncio>=3.4.3",
]
